### ISSUE TITLE
总感觉有一个 bug。

### ISSUE THREAD

**Issue by JellyBool** [overtrue/flysystem-qiniu#1]
看了源码，感觉

https://github.com/overtrue/flysystem-qiniu/blob/master/src/QiniuAdapter.php#L59

这行的 put 方法有一个 bug。这个也可能是 七牛 的 php-sdk 引起的：

https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Storage/FormUploader.php#L14

对比了一下，感觉在 QiniuAdapter.php 中使用 put 是将第二个参数作为 path，而七牛的 php-sdk 是希望传入 name 的。这个时候非常奇怪，如果使用 overtrue/flysystem-qiniu 直接这样：

比如这个是在 https://github.com/overtrue/laravel-ueditor/blob/master/src/QiNiuStorage.php#L33 使用的时候

```php
 public function store(UploadedFile $file, $filename)
    {
        Storage::disk('qiniu')->put($filename, $file);
    }

 public function getUrl($filename)
    {
        return 'http://' . config('filesystems.disks.qiniu.domain') . $filename;
    }
```
好像无论如何 七牛会自动 **再** 加上一个文件名, 比如：

![2017-03-18_14-04-11](https://cloud.githubusercontent.com/assets/6011686/24069517/d25dad4e-0be4-11e7-9b81-63f9a006c9ea.png)

![2017-03-18_14-04-51](https://cloud.githubusercontent.com/assets/6011686/24069512/ada217a6-0be4-11e7-9857-502e184c7137.png)

七牛都把前面的文件名作为路径处理了，再自己加文件 `/4dKRM0FN76R9c7SMjPkHnaYZbIWU5qI7V8UPdufK.jpeg`

**Comment by overtrue** [comment]
@JellyBool https://github.com/qiniu/php-sdk/blob/master/src/Qiniu/Storage/FormUploader.php#L14

> @param $key        上传文件名

$key 就是文件名啊，对于我们的项目来讲就是 path 啊。

```php
public function store(UploadedFile $file, $filename)
{
    Storage::disk('qiniu')->put($filename, $file);
}
```

这样用肯定是错误的，因为 $file 并不是一个 string 的文件名，所以他们会给你生成文件名

**Comment by overtrue** [comment]
@JellyBool 

在 [Flysystem API](http://flysystem.thephpleague.com/api/) 里实际并没有提供按文件路径上传的做法，只有按内容存。

`FormUploader::put()` 是使用二进制流存储，而 `FormUploader::putFile()` 才是按路径上传，所以你的代码应该改成：

```php
public function store(UploadedFile $file, $filename)
{
    Storage::disk('qiniu')->writeStream($filename, fopen($file->getRealPath(), 'r'));
}
```

**Comment by JellyBool** [comment]
@overtrue  OK，我 fix 一下

**Comment by overtrue** [comment]
@JellyBool 不过我可以考虑加一个 API：

```php
public function store(UploadedFile $file, $filename)
{
    Storage::disk('qiniu')->putFile($filename, $file);
}
```

**Comment by overtrue** [comment]
@JellyBool 不过好像也没啥必要哈

**Comment by JellyBool** [comment]
行 @overtrue ，我等下就把 editor 的代码提一波。

七牛这个 putFile() 也挺好，我可以录视频了，哈哈哈。

**Comment by overtrue** [comment]
@JellyBool 哈哈

**Comment by overtrue** [comment]
不加了，你直接按上面的代码来吧，感觉破坏了原子性

**Comment by JellyBool** [comment]
@overtrue 👌
