### ISSUE TITLE
断点续传大文件会失败

### ISSUE THREAD

**Issue by yuyebin** [overtrue/flysystem-qiniu#13]
<img width="827" alt="2018-10-24 15 42 10" src="https://user-images.githubusercontent.com/12133082/47435454-3d3abc00-d7d7-11e8-97c0-bd8fdea9252c.png">

**Comment by overtrue** [comment]
这个在计划中了

**Comment by ayaka209** [comment]
这个我们也遇到了，invalid multipart format: multipart: message too large

**Comment by ayaka209** [comment]
看了一下原因是用了七牛php sdk的put而非putfile
然后没有处理大于4m的情况

**Comment by eeokee** [comment]
也碰到了这个问题，麻烦作者有空修复下

**Comment by overtrue** [comment]
因为这个是 [flysystem](https://github.com/thephpleague/flysystem) 的插件，所以不能随意变动 API ， `put` 方法官方的第二个参数就是文件内容，所以没办法调用 qiniu sdk 的 putFile 方法：
![image](https://user-images.githubusercontent.com/1472352/62220680-09826780-b3e3-11e9-876c-5938ebed7bf9.png)


你们可以试一下用 stream 方式上传：

```php
bool $flysystem->writeStream('large-file.zip', fopen('path/to/your/local/large-file.zip', 'r'));
```

**Comment by eeokee** [comment]
> 因为这个是 [flysystem](https://github.com/thephpleague/flysystem) 的插件，所以不能随意变动 API ， `put` 方法官方的第二个参数就是文件内容，所以没办法调用 qiniu sdk 的 putFile 方法：
> ![image](https://user-images.githubusercontent.com/1472352/62220680-09826780-b3e3-11e9-876c-5938ebed7bf9.png)
> 
> 你们可以试一下用 stream 方式上传：
> 
> ```
> bool $flysystem->writeStream('large-file.zip', fopen('path/to/your/local/large-file.zip', 'r'));
> ```

好的
