### ISSUE TITLE
缩略图这个接口没有找到

### ISSUE THREAD

**Issue by ibmsoft** [overtrue/flysystem-qiniu#15]
PersistentFop

文档地址
https://developer.qiniu.com/dora/manual/1305/processing-results-save-saveas

**Comment by overtrue** [comment]
这个是 flysystem https://github.com/thephpleague/flysystem 的一个适配器，并不是七牛 SDK 的封装，所以只支持通用 API，如果你需要支持拓展功能可以提 PR 以插件方式 https://github.com/overtrue/flysystem-qiniu/tree/master/src/Plugins 来增加方法。
