### ISSUE TITLE
单元测试方法疑惑

### ISSUE THREAD

**Issue by rust17** [overtrue/flysystem-qiniu#21]
https://github.com/overtrue/flysystem-qiniu/blob/b9b2b4c2ce93ccaaabf1a55d76337dcaa54af0b4/tests/QiniuAdapterTest.php#L59
![image](https://user-images.githubusercontent.com/16575052/54106769-23aab180-4412-11e9-9bfc-282a7ee076db.png)

请问此处的 put() 方法是在哪定义的？我在断点调试模式下测试发现此处报错提示方法未定义。正在学习单元测试，不是很懂这块，麻烦超哥解答下哈 😃

**Comment by overtrue** [comment]
@rust17 https://github.com/mockery/mockery 文档读一遍就知道了
