### ISSUE TITLE
上传图片是中文名字时，且生成缩略图为报错

### ISSUE THREAD

**Issue by y284663247** [overtrue/flysystem-qiniu#28]
![image](https://user-images.githubusercontent.com/7445875/62759401-c6478900-bab3-11e9-9f2f-73794662ce6b.png)
个人觉得应该是fopen文件的时候，没有进文件名进行转义，七牛本身对文件名进行转义了

**Comment by overtrue** [comment]
你先保证这张图存在再说吧 `http://hdqn.360qz.com/26/架构.png`

**Comment by overtrue** [comment]
你的 PHP 没有开启 allow_url_fopen 吧？

https://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

**Comment by y284663247** [comment]
![image](https://user-images.githubusercontent.com/7445875/62766620-75409080-bac5-11e9-9b14-50f5629687cd.png)
![image](https://user-images.githubusercontent.com/7445875/62766652-8b4e5100-bac5-11e9-8f7b-33cb87009d77.png)

我测试过，修改成英文名字就可以，中文名字不行，七牛上，中文名字会转义

**Comment by y284663247** [comment]
![image](https://user-images.githubusercontent.com/7445875/62766774-cea8bf80-bac5-11e9-8cb3-905639a9679d.png)

**Comment by y284663247** [comment]
域名是http://hdqn.36qz.com/，不是360qz.com

**Comment by overtrue** [comment]
贴一下你的逻辑代码

**Comment by y284663247** [comment]
我是你这库与laravel-medialibrary一块使用的时候，出现的问题；
为laravel-medialibrary配置disk_name=qiniu,然后有model里面添加一个
```
public function registerMediaConversions(Media $media = null) {
        $this->addMediaConversion('thumb')
            ->width(180)
            ->height(180)
            ->sharpen(10)
            ->fit(Manipulations::FIT_STRETCH,180,180);
    }
```

**Comment by overtrue** [comment]
@y284663247 把截图中的 294 行的 `$path` 换成 `urlencode($path)` 试一下

**Comment by y284663247** [comment]
我看看，提交个request吧

**Comment by overtrue** [comment]
@y284663247 试试 master 分支或者参考我的提交改一下试试，没问题我就发版了。

**Comment by y284663247** [comment]
![image](https://user-images.githubusercontent.com/7445875/62849602-d9a45f80-bd12-11e9-8653-3233df3e9546.png)
OK了，可以了

**Comment by terranc** [comment]
这么改之后导致privateDownloadUrl获取 xxx?avinfo 这种视频信息时404

**Comment by overtrue** [comment]
我艹 @terranc 我要去回滚。。。

**Comment by overtrue** [comment]
@terranc 没有回滚，不过我修复了你说的问题，1.0.4 版本麻烦再试一下

**Comment by terranc** [comment]
@overtrue 没问题，可以把laravel-qiniu一起更新下

**Comment by overtrue** [comment]
那个不需要更新的

Terran <notifications@github.com>于2019年8月17日 周六下午5:13写道：
