### ISSUE TITLE
hyperf框架引入时，上传文件失败

### ISSUE THREAD

**Issue by ricky-2017** [overtrue/flysystem-qiniu#40]
返回[null,{}]

**Comment by overtrue** [comment]
抱歉，其它变种环境请自行排查问题原因哈，此插件是为 fpm 模式准备的，或切换常规 PHP-fpm 环境使用哈。

**Comment by ricky-2017** [comment]
好的~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "安正超"<notifications@github.com&gt;; 
发送时间: 2020年8月26日(星期三) 下午3:04
收件人: "overtrue/flysystem-qiniu"<flysystem-qiniu@noreply.github.com&gt;; 
抄送: "YAKAMOZ"<793212775@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [overtrue/flysystem-qiniu] hyperf框架引入时，上传文件失败 (#40)





 
抱歉，其它变种环境请自行排查问题原因哈，此插件是为 fpm 模式准备的，或切换常规 PHP-fpm 环境使用哈。
