### ISSUE TITLE
七牛云删除返回值不对

### ISSUE THREAD

**Issue by plum-9696** [overtrue/flysystem-qiniu#41]
删除资源，成功删除返回false

**Comment by jonny77** [comment]
我也遇到了这个问题.不管成功与否,返回的都是一个数组.区分就在数组的第二个key. 成功的时候,第二个key是null,失败的时候,第二个key是一个对象..,改成我这样就好了
 $response = $this->getBucketManager()->delete($this->bucket, $path);
        return is_null($response[1]);

**Comment by overtrue** [comment]
https://github.com/thephpleague/flysystem/blob/3.x/src/FilesystemAdapter.php#L53-L59

接口规定了不带返回值哈，不管成功与否
