### ISSUE TITLE
第一版的read和readStream接口，应该直接用privateDownloadUrl更合适一下吧

### ISSUE THREAD

**Issue by augushong** [overtrue/flysystem-qiniu#53]
目前的第一版，的read和readStream接口，是直接通过file_get_content下载cdn域名链接，

这个地方用privateDownloadUrl的连接更好吧。无论bucket是否是公开的，都应该能正常读取。

**Comment by overtrue** [comment]
感谢反馈，已更新

**Comment by augushong** [comment]
相同的问题，第一版能更新发布个版本吗

**Comment by overtrue** [comment]
第一版是指哪个版本？

**Comment by augushong** [comment]
1.0.5，

**Comment by overtrue** [comment]
@augushong https://github.com/overtrue/flysystem-qiniu/releases/tag/1.0.6
