### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by season886** [overtrue/flysystem-qiniu#54]
执行 $this->getAdapter()->getUrl($path) 时会报错
查询是8.1 不允许 使用假布尔值然后再转为数组
版本:1.0.6

**Comment by overtrue** [comment]
麻烦直接贴报错信息而不是翻译一遍，谢谢

**Comment by season886** [comment]
![image](https://user-images.githubusercontent.com/18523125/184277348-a668c0b9-0002-4b03-996f-e5c6f5caa33c.png)

**Comment by overtrue** [comment]
打印该行的 `$result`, `$key`, `$value`

**Comment by season886** [comment]
![image](https://user-images.githubusercontent.com/18523125/184278680-95429daf-e99c-439b-8590-b52ecc31bccc.png)
再往下执行595行就要报错了，只能debug到这给你

**Comment by overtrue** [comment]
修复了，发布了 1.0.7 版本。
