### ISSUE TITLE
七牛云如何获取上传返回值

### ISSUE THREAD

**Issue by StrKang** [overtrue/flysystem-qiniu#55]
![image](https://user-images.githubusercontent.com/44571572/192263011-04fa963c-8e16-42ee-ab76-2896808124a8.png)
我想获取上传后返回的hash和key，但是v1版本以后返回值都被移除了，现在该如何获取

**Comment by overtrue** [comment]
这个包是 flysystem 的适配器，不是 qiniu 专用 SDK，按照 flysystem adapter 的接口， write 就是没有返回值的，key 本身你自己填的，所以无需获取。 
> https://github.com/thephpleague/flysystem/blob/3.x/src/FilesystemAdapter.php#L25-L33

其他接口，可以考虑用官方 SDK：https://github.com/qiniu/php-sdk
