### ISSUE TITLE
我想在上传到七牛时候保存到数据库，该怎么做? 

### ISSUE THREAD

**Issue by tennessine** [overtrue/flysystem-qiniu#6]
或者说，有没有这个必要?

**Comment by overtrue** [comment]
文件名在你手里，你随意处理啊，不光写数据库你要写啥都行

**Comment by tennessine** [comment]
@overtrue 不是的 我是用的laravel-ueditor，但是它上传到七牛之后没有触发事件，所以要扩展只能改源码了。

**Comment by overtrue** [comment]
这样哦，我稍后抽时间优化一下这个
